excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://dborisenko.github.io
title: Denis Borisenko
tagline: Keep cool and smile
description: Hello, my name is Denis and I'm Senior Software Engineer. My main focus is developing applications on Scala (Akka Actor model, Play Framework, Akka Cluster), engineering systems for cloud computing (Amazon AWS, Google Cloud), Reactive Systems.
paginate: 10
